# SwiftLint Configuration for Eater App

# Paths to include for linting
included:
  - .

# Paths to ignore during linting
excluded:
  - Pods
  - .build
  - DerivedData
  - Carthage
  - .swiftpm

# Opt-in rules
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - closure_end_indentation
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - file_header
  - first_where
  - joined_default_parameter
  - literal_expression_end_indentation
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo
  - line_length

# Rule configurations

# File length
file_length:
  warning: 500
  error: 1000

# Type body length
type_body_length:
  warning: 300
  error: 500

# Function body length
function_body_length:
  warning: 50
  error: 100

# Function parameter count
function_parameter_count:
  warning: 5
  error: 8

# Identifier name length
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - db
    - URL
    - i
    - j
    - x
    - y

# Type name length
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - ID
    - URL

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting depth
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# Large tuple
large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  # Prefer using isEmpty over count == 0
  empty_count:
    name: "Empty Count"
    regex: "count\\s*==\\s*0"
    message: "Use 'isEmpty' instead of comparing count to 0"
    severity: warning

  # Require MARK comments
  mark_comment:
    name: "MARK Comment"
    regex: "^\\/\\/\\s*MARK:\\s*-\\s*.+"
    message: "Use MARK comments to organize code sections"
    severity: warning
    match_kinds:
      - comment

# Reporter
reporter: "xcode"
