# XcodeGen Configuration for Paro

name: paro

options:
  bundleIdPrefix: com.paro
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    SWIFT_VERSION: "5.9"
    SUPPORTS_MACCATALYST: NO

targets:
  paro:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: .
        includes:
          - "*.swift"
        excludes:
          - Tests

    settings:
      base:
        PRODUCT_NAME: Paro
        PRODUCT_BUNDLE_IDENTIFIER: com.paro.app
        INFOPLIST_FILE: Info.plist
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic

    scheme:
      testTargets:
        - paroTests
      gatherCoverageData: true

  paroTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/paroTests
    dependencies:
      - target: paro
