# XcodeGen Configuration for Eater iOS App
# Install XcodeGen: brew install xcodegen
# Generate project: xcodegen generate

name: eater

options:
  bundleIdPrefix: com.eater
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    SWIFT_VERSION: "5.9"
    SUPPORTS_MACCATALYST: NO
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO

targets:
  eater:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: .
        includes:
          - "*.swift"
        excludes:
          - Tests
          - docs
          - "*.md"
          - Package.swift
          - Makefile

    settings:
      base:
        PRODUCT_NAME: Eater
        PRODUCT_BUNDLE_IDENTIFIER: com.eater.app
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic

    scheme:
      testTargets:
        - eaterTests
      gatherCoverageData: true

    dependencies:
      # Add Firebase when ready
      # - package: Firebase
      #   product: FirebaseAuth
      # - package: Firebase
      #   product: FirebaseFirestore

  eaterTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - Tests/eaterTests

    dependencies:
      - target: eater

# Package dependencies (add when ready)
# packages:
#   Firebase:
#     url: https://github.com/firebase/firebase-ios-sdk
#     from: "10.0.0"
